# Generated by Django 4.2.9 on 2026-04-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_annotation_coco_segment_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='annotation_type',
            field=models.CharField(choices=[('segmentation_sam', 'Image segmentation (SAM)'), ('segmentation_yolo', 'Instance segmentation (YOLO11-seg)')], default='segmentation_sam', help_text='Determines which model/UI to use; only segmentation (SAM) is active for now.', max_length=32, verbose_name='Annotation task type'),
        ),
        migrations.AlterField(
            model_name='sitebroadcast',
            name='body',
            field=models.TextField(blank=True, default='', help_text='Optional detail text below the title.', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='sitebroadcast',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Shown in the notification dropdown header.', max_length=200, verbose_name='Title'),
        ),
    ]
